Update patch set 3
Patch Set 3:

Patch set 3:
- Fix compilation error: getResources() needs to be called from mContext object.
- Make showPatch a local variable within the method instead. Doesn't need to be an instance variable. Good practice to avoid unnecessary stack memory usage.

Patch-set: 3
Reviewer: Gerrit User 1000140 <1000140@3162e3d8-d894-470e-abd9-724f7b0effad>